[2025-04-22T10:23:51.155-0300] {processor.py:186} INFO - Started process (PID=10377) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:23:51.157-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T10:23:51.161-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:23:51.160-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:23:52.234-0300] {logging_mixin.py:190} INFO - Conexão com o PostgreSQL bem-sucedida
[2025-04-22T10:23:52.658-0300] {logging_mixin.py:190} INFO - Feito
[2025-04-22T10:23:52.658-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:23:52.668-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 1.520 seconds
[2025-04-22T10:25:06.696-0300] {processor.py:186} INFO - Started process (PID=11666) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:25:06.704-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T10:25:06.707-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:25:06.706-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:25:07.960-0300] {logging_mixin.py:190} INFO - Conexão com o PostgreSQL bem-sucedida
[2025-04-22T10:25:08.451-0300] {logging_mixin.py:190} INFO - Feito
[2025-04-22T10:25:08.452-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:25:08.467-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 1.782 seconds
[2025-04-22T10:25:43.214-0300] {processor.py:186} INFO - Started process (PID=12009) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:25:43.215-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T10:25:43.217-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:25:43.217-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:25:44.608-0300] {logging_mixin.py:190} INFO - Conexão com o PostgreSQL bem-sucedida
[2025-04-22T10:25:45.050-0300] {logging_mixin.py:190} INFO - Feito
[2025-04-22T10:25:45.050-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:25:45.063-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 1.855 seconds
[2025-04-22T10:26:47.073-0300] {processor.py:186} INFO - Started process (PID=13079) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:26:47.081-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T10:26:47.087-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:26:47.086-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:26:48.301-0300] {logging_mixin.py:190} INFO - Conexão com o PostgreSQL bem-sucedida
[2025-04-22T10:27:16.665-0300] {logging_mixin.py:190} INFO - Feito
[2025-04-22T10:27:16.667-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:27:16.701-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 29.634 seconds
[2025-04-22T10:28:01.347-0300] {processor.py:186} INFO - Started process (PID=14296) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:28:01.354-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T10:28:01.356-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:28:01.356-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:28:02.643-0300] {logging_mixin.py:190} INFO - Conexão com o PostgreSQL bem-sucedida
[2025-04-22T10:28:31.419-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:28:31.418-0300] {timeout.py:68} ERROR - Process timed out, PID: 14296
[2025-04-22T10:28:31.435-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:28:31.420-0300] {dagbag.py:387} ERROR - Failed to import: /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 104, in <module>
    dim_tempo_venda()
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 100, in dim_tempo_venda
    connection.commit()
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.5/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.5/best-practices.html#reducing-dag-complexity, PID: 14296
[2025-04-22T10:28:31.439-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:28:31.505-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 30.163 seconds
[2025-04-22T10:29:38.789-0300] {processor.py:186} INFO - Started process (PID=15748) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:29:38.796-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T10:29:38.798-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:29:38.797-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:29:40.231-0300] {logging_mixin.py:190} INFO - Conexão com o PostgreSQL bem-sucedida
[2025-04-22T10:30:09.109-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:30:09.108-0300] {timeout.py:68} ERROR - Process timed out, PID: 15748
[2025-04-22T10:30:09.123-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:30:09.111-0300] {dagbag.py:387} ERROR - Failed to import: /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 104, in <module>
    dim_tempo_venda()
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 99, in dim_tempo_venda
    cursor.execute(query)
  File "/usr/lib/python3.12/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
    
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.5/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.5/best-practices.html#reducing-dag-complexity, PID: 15748
[2025-04-22T10:30:09.125-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:30:09.154-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 30.372 seconds
[2025-04-22T10:30:53.079-0300] {processor.py:186} INFO - Started process (PID=16357) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:30:53.085-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T10:30:53.088-0300] {logging_mixin.py:190} INFO - [2025-04-22T10:30:53.088-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:30:54.259-0300] {logging_mixin.py:190} INFO - Conexão com o PostgreSQL bem-sucedida
[2025-04-22T10:30:54.652-0300] {logging_mixin.py:190} INFO - Feito
[2025-04-22T10:30:54.652-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T10:30:54.670-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 1.597 seconds
[2025-04-22T11:07:42.328-0300] {processor.py:186} INFO - Started process (PID=49389) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:07:42.331-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T11:07:42.336-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:07:42.335-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:07:42.356-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:07:42.351-0300] {dagbag.py:387} ERROR - Failed to import: /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 128, in <module>
    elt_()
    ^^^^
NameError: name 'elt_' is not defined
[2025-04-22T11:07:42.358-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:07:42.407-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 0.084 seconds
[2025-04-22T11:08:44.233-0300] {processor.py:186} INFO - Started process (PID=49830) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:08:44.240-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T11:08:44.241-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:08:44.241-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:08:44.246-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:08:44.244-0300] {dagbag.py:387} ERROR - Failed to import: /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 128, in <module>
    elt_()
    ^^^^
NameError: name 'elt_' is not defined
[2025-04-22T11:08:44.247-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:08:44.273-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 0.047 seconds
[2025-04-22T11:09:14.739-0300] {processor.py:186} INFO - Started process (PID=50054) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:09:14.747-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T11:09:14.748-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:09:14.748-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:09:14.755-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:09:14.752-0300] {dagbag.py:387} ERROR - Failed to import: /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 128, in <module>
    elt_()
    ^^^^
NameError: name 'elt_' is not defined
[2025-04-22T11:09:14.756-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:09:14.783-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 0.052 seconds
[2025-04-22T11:10:13.037-0300] {processor.py:186} INFO - Started process (PID=50586) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:10:13.044-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T11:10:13.047-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:10:13.046-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:10:13.055-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:10:13.052-0300] {dagbag.py:387} ERROR - Failed to import: /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 128, in <module>
    elt_()
    ^^^^
NameError: name 'elt_' is not defined
[2025-04-22T11:10:13.057-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:10:13.084-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 0.060 seconds
[2025-04-22T11:10:44.451-0300] {processor.py:186} INFO - Started process (PID=50750) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:10:44.452-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T11:10:44.453-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:10:44.452-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:10:44.457-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:10:44.456-0300] {dagbag.py:387} ERROR - Failed to import: /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 128, in <module>
    elt_()
    ^^^^
NameError: name 'elt_' is not defined
[2025-04-22T11:10:44.459-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:10:44.479-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 0.035 seconds
[2025-04-22T11:11:16.193-0300] {processor.py:186} INFO - Started process (PID=50992) to work on /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:11:16.200-0300] {processor.py:914} INFO - Processing file /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py for tasks to queue
[2025-04-22T11:11:16.201-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:11:16.201-0300] {dagbag.py:588} INFO - Filling up the DagBag from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:11:16.206-0300] {logging_mixin.py:190} INFO - [2025-04-22T11:11:16.204-0300] {dagbag.py:387} ERROR - Failed to import: /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 128, in <module>
    elt_()
    ^^^^
NameError: name 'elt_' is not defined
[2025-04-22T11:11:16.207-0300] {processor.py:927} WARNING - No viable dags retrieved from /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py
[2025-04-22T11:11:16.233-0300] {processor.py:208} INFO - Processing /home/jonathan-brito/python-projects/airflow/dags/dag_etl.py took 0.046 seconds
